Feature/setup
Benawi/Microverse-Reac-Math-Magicians pull request #1
Opened 2023-06-05 15:37 UTC by Benawi

## [Implemented Features](https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/project_setup.md) 
### General requirements
- [x] Make sure that there are no linter errors.
- [x] Make sure that you used the correct Gitflow.
- [x] Make sure that you documented your work in a professional way.
### JavaScript requirements
- [x] Follow our list of best practices for JavaScript.
### Project requirements
- [x] The easiest way to create a React application is using Create React App (CRA) and following the instructions in this [guide](https://reactjs.org/docs/create-a-new-react-app.html#create-react-app).
- [x] The application should run in the browser without errors.

2023-06-05 19:40 UTC, divinecharlotte requested changes
Hi @Benawi        , 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## To Highlight 💯 
- Descriptive readme 👍
- Linters are passing 👍  
- Descriptive pr 👍 

 




 
![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)
## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-05 19:40 UTC, divinecharlotte commented on package.json
> +}
- [ ] kindly consider fixing the error arising in this file to make your app run without errors either in your terminal or the browser as well check the image below to understand clearly the error am talking about there is also a hint to fix it 
<img width="1018" alt="Screen Shot 2023-06-05 at 21 32 59" src="https://github.com/Benawi/Microverse-Reac-Math-Magicians/assets/60146030/7cc8a819-f724-4bb0-a8db-effa36e0879e">

2023-06-06 06:57 UTC, Benawi commented
## Changes ♻
- [x]  Page loadign error fixed [comment](https://github.com/Benawi/Microverse-Reac-Math-Magicians/pull/1#discussion_r1218509872)

![image](https://github.com/Benawi/Microverse-Reac-Math-Magicians/assets/21217148/26b90ada-d082-4c46-a814-69167bf9610c)
![image](https://github.com/Benawi/Microverse-Reac-Math-Magicians/assets/21217148/4ecea490-db76-44e4-958c-eb182489c270)

2023-06-06 07:30 UTC, bobb-Rob approved these changes
## STATUS: APPROVED ✔️ 🍾 🍾 🍾 🥳 🥳 🥳 

Hi @Benawi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-06 09:09 UTC, merged